apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appdynamics-operator-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  - configmaps
  - pods
  verbs:
  - get
  - create
  - update
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - create
  - update
  - list
  - watch
