# permissions for end users to edit containermons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containermon-editor-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - containermons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - containermons/status
  verbs:
  - get
