# permissions for end users to view containermons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containermon-viewer-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - containermons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - containermons/status
  verbs:
  - get
