
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - clustermons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - clustermons/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - clustermons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - containermons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - containermons/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - containermons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - infraagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - infraagents/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - infraagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - servermons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - servermons/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - servermons/status
  verbs:
  - get
  - patch
  - update
