# permissions for end users to view servermons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servermon-viewer-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - servermons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.appdynamics.com
  resources:
  - servermons/status
  verbs:
  - get
